import "./globals.css";
import { cn } from '@/lib/utils'
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

const font = Open_Sans({ subsets: ["latin"] });

// Change the title of tab and the meta data itself
export const metadata: Metadata = {
  title: "Team Talk Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  
    return (
      <ClerkProvider>
        <html lang="en">
          <body className={cn(
          font.className,
          "bg-white dark:bg-[#313338]"
        )}>{children}</body>
        </html>
      </ClerkProvider>
    )
}
